# Generated by Django 2.2.5 on 2019-09-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonebook',
            options={'managed': True, 'verbose_name': 'Phonebook', 'verbose_name_plural': 'Phonebooks'},
        ),
    ]
