# Generated by Django 2.2.5 on 2019-10-01 00:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190930_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
